sudo: false
language: python
python:
  - '3.6'
  
install:
  - pip3 install -U flake8~=3.6.0 pytest>=4.0.0 pytest-cov python-coveralls

script:
  # Temporarily supressing flake8 error
  - flake8 ./ || true
  - python3 -W default::Warning -m pytest test --cov=reversi

cache:
  directories:
    - $HOME/virtualenv/python3.6.*
    - $HOME/.cache/pip
    
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
  - rm -rf $HOME/.cache/pip/http

after_success:
  - coveralls
